name: Compile Linux CLI

on: [push]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup node and load cache
      uses: actions/setup-node@v3
      with:
        node-version: 12.13.0
        cache: yarn
    - name: Install deps
      run: yarn && yarn global add nexe
    - name: Build
      run: yarn build-linux
    - name: Commit and push if there are changes
      run: |-
        git diff
        git config --global user.email "hi@devcomp.tk"
        git config --global user.name "Flight CI"
        git diff --quiet || (git add -u && git commit -m "üì¶Ô∏è Compiled Linux Bins")
        git push     
